// pub const BIND_GROUP_INDEX_SHADER_VALUE: u32 = 5;
// pub const BIND_GROUP_INDEX_SHADER_TEXTURE: u32 = 6;
pub const BIND_GROUP_INDEX_CAMERA_DATA: u32 = 0;
pub const BIND_GROUP_INDEX_LIGHTING_DATA: u32 = 1;

pub const BIND_GROUP_SHADER_PROPERTIES: u32 = 2;

pub const BIND_GROUP_INDEX_PER_FRAME: u32 = 0;
pub const BIND_GROUP_INDEX_PER_OBJECT: u32 = 1;
