[workspace]
members = [
    "druvis-mmd-parser",
    "druvis-core",
    "druvis-test",
]
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

